#!/usr/bin/python

import MySQLdb

#connect to the database
db = MySQLdb.connect("localhost","devanshu","123456","django_db")

#get the cursor
cursor = db.cursor()

sql = "DELETE FROM firstapp_q1q2rightwrong WHERE 1=1;"
cursor.execute(sql)
db.commit()

sql = "SELECT * FROM firstapp_student;"
cursor.execute(sql)
wrong = len(cursor.fetchall())

sql = "SELECT * FROM firstapp_question;"
cursor.execute(sql)

results = cursor.fetchall()

i = 0
length = len(results)
print length
while i < length:
	print "i = " + str(i) + " results[i][0] " + str(results[i][0])
	j = i + 1
	while j < length:
		print "j = " + str(j) + " results[j][0] " + str(results[j][0])
		sql = """INSERT INTO firstapp_q1q2rightwrong(`question_x_id`, `question_y_id`, `right`,`wrong`) VALUES ('%s','%s','%d','%d');""" % (results[i][0],results[j][0],0,wrong)
		cursor.execute(sql)
		db.commit()
		j = j + 1
	i = i + 1

i = 0
while i < length:
	sql = """INSERT INTO firstapp_q1q2rightwrong(`question_x_id`, `question_y_id`, `right`,`wrong`) VALUES ('%s','%s','%d','%d');""" % (results[i][0],results[i][0],0,wrong)
	cursor.execute(sql)
	db.commit()
	i = i + 1

sql = "SELECT * FROM firstapp_q1q2rightwrong;"
cursor.execute(sql)
List = cursor.fetchall()
print "items added : " + str(len(List))

cursor.close()
db.close()
